### ISSUE TITLE
Create MDS graph that represents the diff between all pairs of tables

### ISSUE THREAD

**Issue by Reemh** [Reemh/taco#34]
As a first step the tables are static but for later they could be selected from a list of groups (e.g. taco examples, rna, something else with the same semantic etc.)

**Comment by Reemh** [comment]
The d3 example for MDS graph is assuming that there's additional data that specifies the initial positions of the nodes, then they use the distance matrix to calculate the new positions of the nodes.
However, trying to enhance how they do it, still assumes that there's at least 1 node's position identified somewhere by x,y (presumably the first node).

I feel this is too complicated for no reason, I'll probably try to have a force directed graph instead.

**Comment by sgratzl** [comment]
btw. I used http://scikit-learn.org/stable/modules/generated/sklearn.manifold.MDS.html for computing the mds projection on the server side. There is an option handing in the precomputed dissimilarity matrix

**Comment by Reemh** [comment]
It works now using the coordinates for the nodes (tables) from the calculated MDS in the server.
See #45 for using other data sets than the one I have.
