### ISSUE TITLE
Enable selecting multiple rows in LineUp without the need for ctrl key

### ISSUE THREAD

**Issue by Reemh** [Reemh/taco#73]
In order for the Mac users (i.e. Marc, Nils etc.) to be able to try TaCo they need to be able to select multiple rows in lineup without the need to use the ctrl keyboard key.
I tried to add a `selection` column in LineUp but it seems there's something missing.

**Comment by sgratzl** [comment]
update lineup and try again

**Comment by Reemh** [comment]
It works :) thank you @sgratzl
